CREATE SCHEMA IF NOT EXISTS ADMPROD;

DROP TABLE IF EXISTS ADMPROD.TBOD_FUP_OCORR                   CASCADE;
DROP TABLE IF EXISTS ADMPROD.TBOD_HIST_SIT_ESPECIAL                   CASCADE;
DROP TABLE IF EXISTS ADMPROD.TBOD_OCORR_CRM                 CASCADE;
DROP TABLE IF EXISTS ADMPROD.TBOD_OCORRENCIA                   CASCADE;

create table ADMPROD.TBOD_FUP_OCORR
(
    NR_OCORRENCIA NUMBER(11), 
	ID_OCORRENCIA CHAR(1), 
	NR_SEQUENCIAL NUMBER(3), 
	CD_PERFIL_ORIGEM NUMBER(4) NOT NULL, 
	CD_PERFIL_DESTINO NUMBER(4), 
	DS_FUP_OCORR VARCHAR2(2000), 
	DT_INICIO_FUP_OCORR DATE NOT NULL, 
	DT_FIM_FUP_OCORR DATE, 
	CD_USUARIO_RESP VARCHAR2(15)

);

create table ADMPROD.TBOD_HIST_SIT_ESPECIAL
(
    NR_CGCCPF VARCHAR2(19) NOT NULL, 
	DT_SIT_ESPECIAL DATE NOT NULL, 
	NR_OCORRENCIA NUMBER(11,0) NOT NULL, 
	ID_SIT_ESPECIAL CHAR(1), 
	REGRA CHAR(2)
);

create table ADMPROD.TBOD_OCORR_CRM
(
    ID_OCORR_CRM NUMBER(8) NOT NULL, 
	ID_OCORR_DCMS NUMBER(11)
);

create table ADMPROD.TBOD_OCORRENCIA
(
    NR_OCORRENCIA NUMBER(11), 
	ID_OCORRENCIA CHAR(1), 
	CD_CIR_DENTISTA CHAR(6), 
	CD_EMPRESA CHAR(6), 
	CD_ASSOCIADO CHAR(9), 
	CD_TIPO_OCORR NUMBER(3), 
	CD_SEQ_VISITA_EMPR NUMBER(7), 
	CD_MOTIVO_OCORR NUMBER(4), 
	CD_SEQ_VISITA_CD NUMBER(7), 
	DS_OCORRENCIA VARCHAR2(2100 CHAR) NOT NULL, 
	DT_OCORRENCIA DATE NOT NULL, 
	ID_SITUACAO VARCHAR2(30) NOT NULL, 
	NM_CONTATO VARCHAR2(70), 
	DS_FONE_CONTATO VARCHAR2(20), 
	DT_PRORROGACAO DATE, 
	CD_USUARIO_PRORROG VARCHAR2(15), 
	CD_PRORROG_OCORR NUMBER(2), 
	DT_INCLUSAO_PRORROG DATE, 
	NR_PROTOCOLO_RN395 VARCHAR2(20)
);